### ISSUE TITLE
Trojan Detected?

### ISSUE THREAD

**Issue by SkylarPlayz348** [Twingamerdudes/CreatorOS#1]
I don't know if this is serious or not but why is this popping up:
![image](https://user-images.githubusercontent.com/73512621/219277897-650022b1-43b1-4aaa-b4a6-56058375fa84.png)

**Comment by Twingamerdudes** [comment]
wtf, this shouldn't happen, did you try to run it like an exe? You should use VMware to install the iso. If it is haxm, then ignore it, haxm is made by intel. If it is VMware, then same thing. If it is the iso file, then that is weird, doesn't happen for me or for anyone else.

**Comment by SkylarPlayz348** [comment]
No I just hit download on the iso file

**Comment by Twingamerdudes** [comment]
Then this must be an issue with chrome, now chrome usually likes to flag unknown files that people wouldn't download like iso files (most normal users don't download iso since they don't commonly switch OSes). Just ignore it.

**Comment by SkylarPlayz348** [comment]
This was flagged by Windows Defender

**Comment by Twingamerdudes** [comment]
yeah, windows defender is very inaccurate when it comes to detecting files. Also to make it pop up you have to double-click on the file, that's why I asked if you were trying to open it like an exe. So, there is nothing to worry about.
